/* eslint-disable no-underscore-dangle */
/* eslint-disable no-param-reassign */
import * as _ from 'lodash';
// import * as moment from 'moment';
import { Worksheet, Column, CellValue, Borders, Alignment } from 'exceljs';
import moment from 'moment';
import * as momentTz from 'moment-timezone';

export const numberToLetter = (i: number) => _.toUpper(String.fromCharCode(96 + i));
const lastRowBorder = (worksheet: Worksheet) => {
  worksheet.lastRow.eachCell((cell) => {
    worksheet.getCell(cell.address).border = {
      bottom: { style: 'thin', color: { argb: '000000' } },
    };
  });
};

export interface ParseWorkSheetColumn extends Partial<Column> {
  label: string;
}
interface ParseWorksheetHeaderOption {
  title: string;
  subtitle?: string;
  filters?: Record<string, any>;
  by?: string;
  timezone?: string;
  timestamp?: boolean;
  paddingBottomRows?: number;
  columns: ParseWorkSheetColumn[];
}
export const parseWorksheetHeader = (worksheet: Worksheet, options: ParseWorksheetHeaderOption) => {
  if (!worksheet) return 0;
  const {
    title,
    subtitle,
    filters = {},
    by,
    timezone,
    timestamp = true,
    paddingBottomRows = 2,
    columns = [],
  } = options;

  const columnsCount = columns.length;
  const lastLetter = numberToLetter(columnsCount);
  let i = 0;

  const addHeaderLabel = (value: CellValue) => {
    i++;
    const cellId = `A${i}`;
    const lastCellId = `${lastLetter}${i}`;
    worksheet.addRow({});
    worksheet.mergeCells(cellId, lastCellId);
    const cell = worksheet.getCell(cellId);
    cell.style = { alignment: { horizontal: 'left' }, font: { bold: true } };
    cell.value = value;
  };

  // Add Title
  if (title) {
    i++;
    const cellId = 'A1';
    const lastCellId = `${lastLetter}1`;
    worksheet.addRow({});
    worksheet.mergeCells(cellId, lastCellId);

    const cell = worksheet.getCell(cellId);
    cell.value = title;
    cell.style = {
      alignment: { horizontal: 'center' },
      font: { bold: true, size: 14 },
    };
    lastRowBorder(worksheet);
  }

  // Add Subtitle
  if (subtitle) {
    i++;
    const cellId = 'A2';
    const lastCellId = `${lastLetter}2`;
    worksheet.addRow({});
    worksheet.mergeCells(cellId, lastCellId);

    const cell = worksheet.getCell(cellId);
    cell.value = subtitle;
    cell.style = { alignment: { horizontal: 'center' } };
  }

  _.map(filters, (value, key) => addHeaderLabel(`${_.startCase(key)}:  ${value}`));
  if (timezone) addHeaderLabel(`Timezone: ${timezone}`);
  if (by) addHeaderLabel(`Generated By: ${by}`);
  if (timestamp)
    addHeaderLabel(
      `Generated At:  ${moment.tz('Asia/Kuala_Lumpur').format('DD/MM/YYYY hh:mm:ss A')}`,
    );

  lastRowBorder(worksheet);

  const paddingBottom = [];
  for (let ii = 0; ii < paddingBottomRows; ii++) {
    paddingBottom.push({});
  }
  worksheet.addRows(paddingBottom);
  worksheet.mergeCells(`A${i + 1}`, `${lastLetter}${paddingBottomRows + i}`);

  const tableHeaderRowIndex = 1 + paddingBottomRows + i;
  _.map(columns, (c, index) => {
    const { style, label } = c;
    const cellId = `${numberToLetter(index + 1)}:${tableHeaderRowIndex}`;
    const cell = worksheet.getCell(cellId);
    cell.value = label;
    cell.style = { ...style, font: { bold: true } };
    cell.border = {
      bottom: { style: 'thin', color: { argb: '000000' } },
      top: { style: 'thin', color: { argb: '000000' } },
    };
  });
  worksheet.columns = _.map(columns, (o) => ({ ..._.omit(o, 'label') }));

  return i;
};

export const styleBorderBottom = (worksheet: Worksheet, columns: ParseWorkSheetColumn[]) => {
  const row = worksheet.lastRow;
  const lastRowIndex = row.number;
  const borderBottom: Partial<Borders> = {
    bottom: { style: 'thin', color: { argb: '000000' } },
  };
  _.map(columns, (_c, index) => {
    const cellId = `${numberToLetter(index + 1)}:${lastRowIndex}`;
    const cell = worksheet.getCell(cellId);
    cell.border = borderBottom;
  });
};

export const parseFileName = (reportName: string, ext = 'xlsx') =>
  `${reportName}-${moment().format('YYYYMMDDHHmmssSSS')}.${ext}`;

export const style = {
  center: { alignment: { horizontal: 'center' } as Partial<Alignment> },
  right: { alignment: { horizontal: 'right' } as Partial<Alignment> },
  RM: { numFmt: '"RM"#,##0.00;[Red]-"RM"#,##0.00' },
};
