/**
 * @file Automatically generated by barrelsby.
 */

export * from './customer-addresses.authorizer';
export * from './customer-addresses.input';
export * from './customer-addresses.module';
export * from './customer-addresses.resolver';
export * from './customer-addresses.service';
export * from './customer-addresses.subscriber';
