/**
 * @file Automatically generated by barrelsby.
 */

export * from './admins-roles-permissions.authorizer';
export * from './admins-roles-permissions.input';
export * from './admins-roles-permissions.module';
export * from './admins-roles-permissions.resolver';
export * from './admins-roles-permissions.service';
export * from './admins-roles-permissions.subscriber';
