/**
 * @file Automatically generated by barrelsby.
 */

export * from './area-of-service.authorizer';
export * from './area-of-service.input';
export * from './area-of-service.module';
export * from './area-of-service.resolver';
export * from './area-of-service.service';
export * from './area-of-service.subscriber';
